// Code generated by goctl. DO NOT EDIT.
package types

type SpiderRequest struct {
	Uid []uint32 `json:"uid"`
}

type SpiderResponse struct {
	Message string `json:"message"`
}

type AliYunCallbackReq struct {
	AccessToken string `form:"code"`
}

type AliYunCallbackResp struct {
	Code        uint32 `json:"code"`        // 状态码
	Message     string `json:"message"`     // 信息
	AccessToken string `json:"accessToken"` // accesstoken
}
